// Bundles server/vercel-entry.ts into api/index.js as a single self-contained
// CommonJS file. Vercel's @vercel/node runtime then deploys it as the function
// handler for all /api/* requests (per the rewrite in vercel.json).
//
// We do this manually because Vercel's auto-bundler does not include sibling
// directories like server/ when imported from api/index.ts.
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";

mkdirSync("api", { recursive: true });

const result = await build({
  entryPoints: ["server/vercel-entry.ts"],
  bundle: true,
  platform: "node",
  target: "node22",
  format: "cjs",
  outfile: "api/index.js",
  external: ["@vercel/node"],
  logLevel: "info",
  banner: {
    js: "// AUTO-GENERATED by scripts/build-api.mjs — do not edit",
  },
  metafile: true,
});

const outputs = Object.entries(result.metafile.outputs);
for (const [path, info] of outputs) {
  console.log(`  ${path}: ${(info.bytes / 1024).toFixed(1)} KB`);
}

// Vercel's @vercel/node@5 builds .ts/.js entrypoints by re-running esbuild over them.
// Since we've already bundled, we want it to leave the file alone.
// Adding a `vercel.json` `functions` config with our own runtime is one way; the
// simpler way is to re-export bundled CJS through a tiny wrapper, but Vercel will
// still try to walk imports. So instead, drop a dummy package.json next to our
// function to mark it as the deployment root for that function:
writeFileSync("api/package.json", JSON.stringify({ type: "commonjs" }, null, 2));
console.log("Wrote api/package.json (type=commonjs)");
